name: Trigger Website Action

on:
  push:
    branches:
      - main

jobs:
  trigger-website-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Trigger Website Action
        run: |
          curl -XPOST \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }} " \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" \
            -d "{\"event_type\": \"docs-updated\"}" \
            "https://api.github.com/repos/PKM-er/Pkmer-Website/dispatches"
